{
  imports = [
    ./bluetooth.nix
    ./bootloader.nix
    ./fcitx.nix
    ./fonts.nix
    ./nh.nix
    ./hyprland.nix
    ./locale.nix
    ./networking.nix
    ./nix-ld.nix
    ./nixsettings.nix
    ./nvidia.nix
    ./packages.nix
    ./services.nix
    ./sound.nix
    ./steam.nix
    ./stylix.nix
    ./users.nix
    ./virtualisation.nix
    ./firewall.nix
    ./dwm.nix
  ];
}
