windowrule = match:title ^launcher$, float 1
windowrule = match:title ^launcher$, size 500 430
windowrule = match:title ^launcher$, center 1

windowrule = match:initial_class steam, workspace special:hyprspace
