{
  flake.nixosModules.zapret = {
    services.zapret = {
      enable = false;
      params = [
        "tpws --hostpad=8192"
        "tpws --split-pos=method+2 --oob"
        "tpws --unixeol"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=5 --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fake --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=0 --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fake --dpi-desync-fooling=ts --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fake --dpi-desync-fooling=md5sig --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-ttl=5 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=0 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-fooling=datanoack --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-fooling=ts --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-fooling=md5sig --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=5"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=badsum"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=0"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=datanoack"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=ts"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=md5sig"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-ttl=5 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=0 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-fooling=datanoack --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-fooling=ts --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-fooling=md5sig --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=multisplit --dpi-desync-split-pos=method+2 --dpi-desync-split-seqovl=1"
        "nfqws --dpi-desync=multisplit --dpi-desync-split-pos=method+2,midsld --dpi-desync-split-seqovl=1"
        "nfqws --dpi-desync=multidisorder --dpi-desync-split-pos=method+2 --dpi-desync-split-seqovl=method+1"
        "nfqws --dpi-desync=multidisorder --dpi-desync-split-pos=midsld --dpi-desync-split-seqovl=midsld-1"
        "nfqws --dpi-desync=multidisorder --dpi-desync-split-pos=method+2,midsld --dpi-desync-split-seqovl=method+1"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-1 --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-2 --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-3 --dpi-desync-fake-http=0x00000000"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=-1 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=-2 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakedsplit --dpi-desync-ttl=1 --dpi-desync-autottl=-3 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-2"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-3"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=-1 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=-2 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fakeddisorder --dpi-desync-ttl=1 --dpi-desync-autottl=-3 --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=syndata"
        "nfqws --dpi-desync=syndata,multisplit --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=syndata,multidisorder --dpi-desync-split-pos=method+2"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=5 --dpi-desync-fake-tls=0x1603 --dpi-desync-fake-tls=!+2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni --dpi-desync-fake-tcp-mod=seq"
        "nfqws --dpi-desync=fake --dpi-desync-fooling=badseq --dpi-desync-fake-tls=0x00000000 --dpi-desync-fake-tls=! --dpi-desync-fake-tls-mod=rnd,rndsni,dupsid"
        "nfqws --dpi-desync=fake --dpi-desync-fooling=ts --dpi-desync-fake-tls=0x1603 --dpi-desync-fake-tls=!+2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni --dpi-desync-fake-tcp-mod=seq"
        "nfqws --dpi-desync=fake --dpi-desync-fooling=md5sig --dpi-desync-fake-tls=0x1603 --dpi-desync-fake-tls=!+2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni --dpi-desync-fake-tcp-mod=seq"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=5 --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=badseq --dpi-desync-badseq-increment=0 --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=datanoack --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=ts --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-fooling=md5sig --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-1 --dpi-desync-fake-tls=0x1603 --dpi-desync-fake-tls=!+2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni --dpi-desync-fake-tcp-mod=seq"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-2 --dpi-desync-fake-tls=0x1603 --dpi-desync-fake-tls=!+2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni --dpi-desync-fake-tcp-mod=seq"
        "nfqws --dpi-desync=fake --dpi-desync-ttl=1 --dpi-desync-autottl=-3 --dpi-desync-fake-tls=0x1603 --dpi-desync-fake-tls=!+2 --dpi-desync-fake-tls-mod=rnd,dupsid,rndsni --dpi-desync-fake-tcp-mod=seq"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-1 --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-2 --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=hostfakesplit --dpi-desync-ttl=1 --dpi-desync-autottl=-3 --dpi-desync-hostfakesplit-mod=altorder=1"
        "nfqws --dpi-desync=syndata"
        "nfqws --dpi-desync=syndata,multisplit --dpi-desync-split-pos=1"
        "nfqws --dpi-desync=syndata,multidisorder --dpi-desync-split-pos=1"
        "nfqws --dpi-desync=fake --dpi-desync-repeats=5"
      ];
    };
  };
}
