{
    imports = [
      ./git.nix
      ./kitty.nix
      ./spicetify.nix
      ./hyprland.nix
      ./waybar.nix
      ./rofi.nix
      ./sh.nix
      ./starship.nix
      ./xdg.nix
      ./qt.nix
      ./tmux.nix
      ./hypridle.nix
      ./hyprlock.nix
      ./zoxide.nix
      ./stylix.nix
      ./ghostty.nix
    ];
}
