{
  imports = [
    ./git.nix
    ./spicetify.nix
    ./hyprland.nix
    ./waybar.nix
    ./rofi.nix
    ./sh.nix
    ./starship.nix
    ./qt.nix
    ./tmux.nix
    ./hypridle.nix
    ./hyprlock.nix
    ./zoxide.nix
    ./stylix.nix
    ./ghostty.nix
    ./sherlock.nix
    ./ncmpcpp.nix
    ./mpd.nix
    ./rmpc.nix
  ];
}
