{
  imports = [
    ./dunst.nix
    ./ghostty.nix
    ./git.nix
    ./gtk.nix
    ./hypridle.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./kitty.nix
    ./mpd.nix
    ./ncmpcpp.nix
    ./qt.nix
    ./rofi.nix
    ./sh.nix
    ./starship.nix
    ./stylix.nix
    ./tmux.nix
    ./waybar.nix
    ./wezterm.nix
    ./zoxide.nix
    ./jujutsu.nix
    ./mako.nix
    ./quickshell.nix
    ./fuzzel.nix
  ];
}
