{
  imports = [
    ./bootloader.nix
    ./fonts.nix
    ./garbaceCollector.nix
    ./nvidia.nix
    ./packages.nix
    ./services.nix
    ./users.nix
    ./nixsettings.nix
    ./locale.nix
    ./networking.nix
    ./sound.nix
    ./uwsm.nix
    ./hyprland.nix
    ./polkit.nix
    ./steam.nix
    ./virtualisation.nix
  ];
}
